#include <windows.h>
#include <shlobj_core.h>
#include <shobjidl_core.h>
#include <wrl/client.h>
#include <string>
#include <atomic>

namespace {
std::atomic<long> g_objects{0}, g_locks{0}; constexpr wchar_t MetadataKey[] = L"ContextMenuMgrShellProxy";
bool ReadOriginal(CLSID proxy, CLSID& original, std::wstring& title) { wchar_t text[64]{}; StringFromGUID2(proxy,text,64); HKEY roots[]{HKEY_CURRENT_USER,HKEY_LOCAL_MACHINE}; for(auto root:roots){std::wstring path=root==HKEY_CURRENT_USER?L"Software\\Classes\\CLSID\\":L"SOFTWARE\\Classes\\CLSID\\"; path+=text; path+=L"\\"; path+=MetadataKey; HKEY key{}; if(RegOpenKeyExW(root,path.c_str(),0,KEY_READ,&key)!=ERROR_SUCCESS)continue; wchar_t raw[64]{},caption[261]{}; DWORD type{},bytes=sizeof(raw); auto result=RegQueryValueExW(key,L"OriginalHandlerClsid",nullptr,&type,reinterpret_cast<BYTE*>(raw),&bytes); bytes=sizeof(caption);RegQueryValueExW(key,L"MenuTitle",nullptr,&type,reinterpret_cast<BYTE*>(caption),&bytes);RegCloseKey(key);if(result==ERROR_SUCCESS&&SUCCEEDED(CLSIDFromString(raw,&original))&&!IsEqualCLSID(proxy,original)){title=caption;return !title.empty();}}return false;}
bool IsProxyClsid(CLSID id){wchar_t text[64]{};StringFromGUID2(id,text,64);for(auto root:{HKEY_CURRENT_USER,HKEY_LOCAL_MACHINE}){std::wstring path=root==HKEY_CURRENT_USER?L"Software\\Classes\\CLSID\\":L"SOFTWARE\\Classes\\CLSID\\";path+=text;path+=L"\\";path+=MetadataKey;HKEY key{};if(RegOpenKeyExW(root,path.c_str(),0,KEY_READ,&key)==ERROR_SUCCESS){RegCloseKey(key);return true;}}return false;}
bool HasUsableItem(HMENU menu){for(int i=0;i<GetMenuItemCount(menu);++i){MENUITEMINFOW info{sizeof(info)};info.fMask=MIIM_FTYPE;if(GetMenuItemInfoW(menu,i,TRUE,&info)&&(info.fType&MFT_SEPARATOR)==0)return true;}return false;}
class Proxy final:public IShellExtInit,public IContextMenu3{public:explicit Proxy(CLSID id):id_(id){++g_objects;}~Proxy(){--g_objects;}HRESULT STDMETHODCALLTYPE QueryInterface(REFIID iid,void**v)override{if(!v)return E_POINTER;*v=nullptr;if(iid==IID_IUnknown||iid==IID_IShellExtInit)*v=static_cast<IShellExtInit*>(this);else if(iid==IID_IContextMenu||iid==IID_IContextMenu2||iid==IID_IContextMenu3)*v=static_cast<IContextMenu3*>(this);else return E_NOINTERFACE;AddRef();return S_OK;}ULONG STDMETHODCALLTYPE AddRef()override{return ++refs_;}ULONG STDMETHODCALLTYPE Release()override{auto v=--refs_;if(!v)delete this;return v;}HRESULT STDMETHODCALLTYPE Initialize(PCIDLIST_ABSOLUTE folder,IDataObject*data,HKEY key)override{CLSID original{};if(!ReadOriginal(id_,original,title_)||IsProxyClsid(original))return E_FAIL;auto hr=CoCreateInstance(original,nullptr,CLSCTX_INPROC_SERVER,IID_IUnknown,reinterpret_cast<void**>(handler_.GetAddressOf()));if(FAILED(hr))return hr;if(FAILED(handler_.As(&init_))||FAILED(handler_.As(&menu_)))return E_NOINTERFACE;handler_.As(&menu3_);handler_.As(&menu2_);return init_->Initialize(folder,data,key);}HRESULT STDMETHODCALLTYPE QueryContextMenu(HMENU parent,UINT index,UINT first,UINT last,UINT flags)override{if(!menu_)return E_FAIL;HMENU child=CreatePopupMenu();if(!child)return E_OUTOFMEMORY;auto hr=menu_->QueryContextMenu(child,0,first,last,flags);if(FAILED(hr)||!HasUsableItem(child)){DestroyMenu(child);return FAILED(hr)?hr:MAKE_HRESULT(SEVERITY_SUCCESS,0,0);}MENUITEMINFOW info{sizeof(info)};info.fMask=MIIM_SUBMENU|MIIM_STRING;info.hSubMenu=child;info.dwTypeData=const_cast<wchar_t*>(title_.c_str());if(!InsertMenuItemW(parent,index,TRUE,&info)){DestroyMenu(child);return HRESULT_FROM_WIN32(GetLastError());}return hr;}HRESULT STDMETHODCALLTYPE InvokeCommand(LPCMINVOKECOMMANDINFO c)override{return menu_?menu_->InvokeCommand(c):E_FAIL;}HRESULT STDMETHODCALLTYPE GetCommandString(UINT_PTR id,UINT type,UINT*reserved,CHAR*name,UINT cch)override{return menu_?menu_->GetCommandString(id,type,reserved,name,cch):E_FAIL;}HRESULT STDMETHODCALLTYPE HandleMenuMsg(UINT m,WPARAM w,LPARAM l)override{if(menu3_){LRESULT r{};return menu3_->HandleMenuMsg2(m,w,l,&r);}return menu2_?menu2_->HandleMenuMsg(m,w,l):S_OK;}HRESULT STDMETHODCALLTYPE HandleMenuMsg2(UINT m,WPARAM w,LPARAM l,LRESULT*r)override{if(r)*r=0;return menu3_?menu3_->HandleMenuMsg2(m,w,l,r):menu2_?menu2_->HandleMenuMsg(m,w,l):S_OK;}private:std::atomic<ULONG>refs_{1};CLSID id_{};std::wstring title_;Microsoft::WRL::ComPtr<IUnknown>handler_;Microsoft::WRL::ComPtr<IShellExtInit>init_;Microsoft::WRL::ComPtr<IContextMenu>menu_;Microsoft::WRL::ComPtr<IContextMenu2>menu2_;Microsoft::WRL::ComPtr<IContextMenu3>menu3_;};
class Factory final:public IClassFactory{public:explicit Factory(CLSID id):id_(id){}HRESULT STDMETHODCALLTYPE QueryInterface(REFIID iid,void**v)override{if(!v)return E_POINTER;*v=nullptr;if(iid!=IID_IUnknown&&iid!=IID_IClassFactory)return E_NOINTERFACE;*v=this;AddRef();return S_OK;}ULONG STDMETHODCALLTYPE AddRef()override{return ++refs_;}ULONG STDMETHODCALLTYPE Release()override{auto v=--refs_;if(!v)delete this;return v;}HRESULT STDMETHODCALLTYPE CreateInstance(IUnknown*outer,REFIID iid,void**v)override{if(outer)return CLASS_E_NOAGGREGATION;auto proxy=new(std::nothrow)Proxy(id_);if(!proxy)return E_OUTOFMEMORY;auto hr=proxy->QueryInterface(iid,v);proxy->Release();return hr;}HRESULT STDMETHODCALLTYPE LockServer(BOOL lock)override{lock?++g_locks:--g_locks;return S_OK;}private:std::atomic<ULONG>refs_{1};CLSID id_{};};}
BOOL APIENTRY DllMain(HMODULE,DWORD,LPVOID){return TRUE;}STDAPI DllGetClassObject(REFCLSID id,REFIID iid,void**v){auto factory=new(std::nothrow)Factory(id);if(!factory)return E_OUTOFMEMORY;auto hr=factory->QueryInterface(iid,v);factory->Release();return hr;}STDAPI DllCanUnloadNow(void){return g_objects==0&&g_locks==0?S_OK:S_FALSE;}
